# Generated by Django 4.1.3 on 2022-11-08 14:33

import core.handlers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to=core.handlers.file_upload_handler)),
                ("slug", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
