# Generated by Django 4.1.3 on 2022-11-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
